### ISSUE TITLE
Opret Hall

### ISSUE THREAD

**Issue by dotCyanidez** [dotCyanidez/TheMovies#4]
Opret Hall model 
Opret HallRepo med metoder vist i DCD

**Comment by Abarbesgaard** [comment]
[Link til UML](https://app.diagrams.net/#G1rpRFNC7fp4prhnQpLc0lmanc_f54sped)

**Comment by Abarbesgaard** [comment]
Hall er færdig implementeret men repo mangler alt connection til DB
